"""make hcp_id nullable

Revision ID: d45b6a2fd1aa
Revises: 6a89b62b1a8b
Create Date: 2026-04-06 19:05:17.822485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45b6a2fd1aa'
down_revision: Union[str, None] = '6a89b62b1a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions', 'hcp_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions', 'hcp_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
